name: Development Build

on:
  push:
    branches:
        - dev
        - dev*
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  CI: true
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: License
        run: pnpm license

      - name: Compile
        run: pnpm build --verbose

      - name: Build
        run: rojo build --output game.rbxlx

      - name: Upload place artifact
        uses: actions/upload-artifact@v4
        with:
          name: game.rbxlx
          path: game.rbxlx

  deploy:
    runs-on: ubuntu-latest
    environment: development
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: CompeyDev/setup-rokit@v0.1.2

      - name: Download place artifact
        uses: actions/download-artifact@v4
        with:
          name: game.rbxlx
      
      - name: Deploy game
        run: mantle deploy --environment dev
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_OPEN_CLOUD_API_KEY: ${{ secrets.MANTLE_OPEN_CLOUD_API_KEY }}
      

